// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qivqzhlgbvbtkobqccsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdnF6aGxnYnZidGtvYnFjY3N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1Mzk1MjQsImV4cCI6MjA2MjExNTUyNH0.KHmkj3d4YPtFW_7zdlP9ldq3Fpp3dKziCkpqLmANqBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);